on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  # Run this repositories pre-commit hooks.
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.47.0
      - uses: pre-commit/action@v3.0.0
